include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    flutter_style_todos: true
    use_key_in_widget_constructors: true
